### ISSUE TITLE
ex) 03 Odroid& Hosts 환경설정 16p_Minicon

### ISSUE THREAD

**Issue by baaami** [Livenow14/2020_INU_Embedded_System#1]
usb2.0 포트와 연결시 vmware와 연결이 잘 되지 않는 것 같습니다. 아직 이더넷을 연결시키지 않고 minicom을 설정하고 있었는데 이더넷 문제인지 혹시 디바이스 드라이버나 필요한 부분이 있나요?

![image](https://user-images.githubusercontent.com/52270698/78031273-46ea2b00-739e-11ea-92ba-983fb2e57daf.png)

스크린샷과 같이 첨부합니다

root@ubuntu:/home/seongbm# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 0e0f:0008 VMware, Inc. 
Bus 002 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 002 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
root@ubuntu:/home/seongbm# sudo ls -lsa /dev/tty* | grep USB
root@ubuntu:/home/seongbm# sudo ls -lsa /dev/tty* | grep USB
root@ubuntu:/home/seongbm# sudo ls -lsa /dev/tty* | grep USB
root@ubuntu:/home/seongbm# grep /dev/tty*
^C
root@ubuntu:/home/seongbm# dmesg | grep tty
[    1.108258] printk: console [tty0] enabled
[    4.047448] 00:05: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
root@ubuntu:/home/seongbm# sud

**Comment by Livenow14** [comment]
다음주에 환경설정하는 방법이 동영상으로 올라올 예정입니다. 
어떻게 설정하는지 알려 드릴 순 있지만, 저번주에 키트가 발송되었고, 키트를 늦게 받을 수 있는 학생이 있다는 것을 고려하여 결정된 진도이니 먼저 나가지 마시고 천천히 기다려 주세요 :)
