### ISSUE TITLE
03 Odroid Host 환경설정

### ISSUE THREAD

**Issue by Nyppp** [Livenow14/2020_INU_Embedded_System#2]
![image](https://user-images.githubusercontent.com/63279872/78634596-3f1b1100-78df-11ea-8b63-718a2960efba.png)

toolchain 설치과정에서 
![image](https://user-images.githubusercontent.com/63279872/78634631-55c16800-78df-11ea-810d-f66654f37303.png)
lib32stdc++6, lib32z1 두개에 대해서 패키지를 찾을 수 없다고 나오며 설치가 안됩니다. 그 외에는 모두 정상적으로 설치가 됩니다.
우분투 버전은 14.04이고, VM 대신 Oracle Virtual Box 사용중입니다.

**Comment by Livenow14** [comment]
3가지의 문제라고 생각할 수 있습니다. 
 1. sudo apt-get update를 안함. 
  -> sudo apt-get update를 터미널에 입력

2. 32비트 / 64비트 차이 문제 
  -> 받으려는 패키지가 32비트에서 지원을 안할 수 있습니다. 수업 영상에서는 ubuntu 18.04 64bit를 설치하여서 진행하기 때문에 오류가 생기지 않았던 건데요. 학생의 우분투 운영체제 bit를 확인해보고, 32비트면 수업 영상과 같이 다시 설치 진행을 해주시길 바랍니다. 

3. 버전 문제 
  -> 메인페이지에 버전은 크게 상관없다고 하였지만, 테스트는 16.04/18.04버전에서 실행하였습니다.  그렇기때문에 14.04에서는 lib32stdc++6을 지원을 안할수도 있습니다. 위와같은 방법이 해결이 안될 시  16.04 버전이나 18.04버전으로 재설치 해주세요

웬만하면 수업 영상에서 실시한 것과 같은 환경을 만들어주세요!
이후 수업에서 생기는 오류가 이러한 버전문제, bit 문제일 가능성이 높기 때문입니다. 

또 궁금한거 있으시면 댓글 남겨주세요
