### ISSUE TITLE
버튼을 입력받는데 문제가 있어 질문 드립니다

### ISSUE THREAD

**Issue by WhiteHyun** [Livenow14/2020_INU_Embedded_System#22]
가감산기 구현은 완료하였는데, 버튼을 입력했을 때 열의 일곱은 다른 버튼이 눌려지는 것처럼 입력이됩니다. 예를들어 제가 8에 해당하는 버튼을 눌렀을 때 7이 눌린 것으로 인식한다거나 드물게 4가 인식되거나 합니다. 이 같은 문제에 대해 이유를 정확히 모르겠어서 질문드립니다.

**Comment by WhiteHyun** [comment]
![KakaoTalk_20200514_144304606](https://user-images.githubusercontent.com/57972338/81897444-98b6df80-95f1-11ea-8618-a6a7b979f7b4.jpg)

버튼 2를 일정한 속도로 눌렀을 때 저렇게 나타납니다

**Comment by Livenow14** [comment]
입력을 받는 방식에 오류가 있는 것 같습니다. 
하드웨어는 우리가 일반적으로 생각하는 것과 다르게 ms로 입력을 받기때문에 여러 입력이 들어갑니다.
이 이상은 과제에 직접적인 질문이라 알려드릴 수 없습니다. 감사합니다.

**Comment by WhiteHyun** [comment]
ms로 입력을 받는다는게 무슨 말씀이신지 정확한 의미를 모르겠습니다. ms가 무엇인지 여쭤봐도 될까요?

**Comment by Livenow14** [comment]
millisecond 약어입니다.
