### ISSUE TITLE
+ 기호 예외처리에 관해 질문 사항있습니다.

### ISSUE THREAD

**Issue by WhiteHyun** [Livenow14/2020_INU_Embedded_System#30]
lab PPT에 보았을 때 +: 합, -:차, 최초에 입력되면 minus 기호라고 써져있습니다.
+에 대해서는 최초라는 언급이 없어서 이를 어떻게 해야할까 고민하고있는데 한 학생은 계산기는 0부터 시작이니 +2라고 입력받았을 경우 2가 나오게끔 출력을 했다. 라고하고, 다른 한 학생은 최초라는 언급을 -에만 했으니 처음 +를 입력받으려 하면 오류가 나오게끔 하였다. 라고 하더군요.
이에 대한 명확한 언급이 없어 질문드립니다.

**Comment by Livenow14** [comment]
언급이 없었던 부분에 대해서는 채점하지 않습니다. 
일반적인 계산기에서 어떻게 진행되는지 생각해보시고, 
본인 스타일의 계산기를 만든다고 생각해주세요

**Comment by WhiteHyun** [comment]
답변 감사드립니다.
