### ISSUE TITLE
알파벳 폰트 질문드립니다.

### ISSUE THREAD

**Issue by WhiteHyun** [Livenow14/2020_INU_Embedded_System#40]
알파벳 폰트를 직접 a~z, . 까지 일일히 만들으라는 말씀이신건가요?
만약 맞다면, 24x24 글자 크기 내에서 꽉 채워서 만들어야하는지 아니면 24x24 내에 문자를 적당하게 만들면 되는건지 답변 부탁드립니다(PPT 내에서는 글자 사이 4pixel을 띄움으로 되어있는데, 글자 크기가 24x24 규격 내에 글자가 만들어져 있는 경우 LCD에 표기 되는 것이 4pixel을 넘어갈 수 있어서 점수에 차질이 발생할 수 있을 거라 판단했기에 질문드립니다).

**Comment by Livenow14** [comment]
1. 일반 사용자가 문자를 확인할 수 있을 만큼. 이라 생각하시면 될 것 같습니다. 
이에 대한 답변은 https://github.com/Livenow14/2020_INU_Embedded_System/issues/39
이부분을 확인해주세요
