### ISSUE TITLE
라이브러리 선언에 대해 질문 있습니다.

### ISSUE THREAD

**Issue by WhiteHyun** [Livenow14/2020_INU_Embedded_System#43]
공지사항에 "라이브러리는 지정해준 라이브러리만 사용하여 주세요" 라고 하셨는데, 그렇다면
#include <stdbool.h> 이나 #include <time.h> 와 같은 라이브러리를 사용해서는 안된다는 말씀이신건지 궁금합니다.
![image](https://user-images.githubusercontent.com/57972338/84015767-4f22a000-a9b7-11ea-98b3-4a5135664488.png)

**Comment by Livenow14** [comment]
'지정해준 라이브러리'에 대한 설명이 부족했다고 생각됩니다.
지금까지 ppt에 나왔던 라이브러리로도 과제를 해결할 수 있기에 지정해준 라이브러리만 사용하라고 명시하였습니다. 
 다만 과제의 직접적인 해결에 관여하지 않는 라이브러리. 즉 학생이 질문한 라이브러리는 사용이 가능합니다.
Lab3까지 진행하였다면, 직접적으로 과제를 쉽게 해결하게 도와주는 라이브러리와 과제를 해결하기 위해 도움을 주는 라이브러리에 대한 차이점을 파악하시리라 생각됩니다.
 추가적인 라이브러리는 본인의 리포트에 명시하여 그 쓰임새에 대해 설명을 하면 됩니다.

**Comment by WhiteHyun** [comment]
상세한 답변 감사드립니다. 이슈 닫도록 하겠습니다.
