### ISSUE TITLE
lab3 질문

### ISSUE THREAD

**Issue by ppyppp** [Livenow14/2020_INU_Embedded_System#45]
폰트는 소문자로만 만들어야 하는지 궁금합니다. 
또 공백을 출력하라고 하셨는데 문자들 사이에  커서가 있는 경우에도 공백 출력이 되어야 하는지 궁금합니다.

**Comment by Livenow14** [comment]
폰트는 소문자로 하든, 대문자로 하든 상관없습니다. 
일관성만 지켜주세요 

문자들 사이에 커서가 있다는 얘기가 이해하기 힘드네요.
어떤 경우에서든지 공백을 출력하세요. 
폴더폰의 메세지 방식을 생각하면 되겠네요.
